AWS:
- name: AWS CLI
  pkg: aws-cli
  post-install: null
  post-remove: null
  pre-install: null
  pre-remove: null
  remove: null
  status: UnInstalled
- name: AWS CLI V2
  pkg: aws-cli-v2
  post-install: null
  post-remove: null
  pre-install: null
  pre-remove: null
  remove: null
  status: UnInstalled
Configuration Management:
- name: Ansible
  pkg: ansible
  post-install: null
  post-remove: null
  pre-install: null
  pre-remove: null
  remove: null
  status: Installed
- name: Nix
  pkg: nix
  post-install: null
  post-remove: null
  pre-install: null
  pre-remove: null
  remove: null
  status: UnInstalled
Containerization:
- name: Docker
  pkg: docker
  post-install: null
  post-remove: null
  pre-install: null
  pre-remove: null
  remove: null
  status: Installed
- name: Docker Compose
  pkg: docker-compose
  post-install: null
  post-remove: null
  pre-install: null
  pre-remove: null
  remove: null
  status: Installed
- name: Podman
  pkg: podman
  post-install: null
  post-remove: null
  pre-install: null
  pre-remove: null
  remove: null
  status: Installed
- name: Podman Compose
  pkg: podman-compose
  post-install: null
  post-remove: null
  pre-install: null
  pre-remove: null
  remove: null
  status: Installed
- name: Podman Desktop
  pkg: podman-desktop
  post-install: null
  post-remove: null
  pre-install: null
  pre-remove: null
  remove: null
  status: Installed
IaaC:
- name: Terraform
  pkg: terraform
  post-install: null
  post-remove: null
  pre-install: null
  pre-remove: null
  remove: null
  status: UnInstalled
- name: Pulumi
  pkg: pulumi
  post-install: null
  post-remove: null
  pre-install: null
  pre-remove: null
  remove: null
  status: UnInstalled
Orchestration (K8s):
- name: Kubelet
  pkg: kubelet
  post-install: null
  post-remove: null
  pre-install: null
  pre-remove: null
  remove: null
  status: UnInstalled
- name: Kubeadm
  pkg: kubeadm
  post-install: null
  post-remove: null
  pre-install: null
  pre-remove: null
  remove: null
  status: UnInstalled
- name: Kubectl
  pkg: kubectl
  post-install: null
  post-remove: null
  pre-install: null
  pre-remove: null
  remove: null
  status: UnInstalled
- name: MiniKube (Recom. install on VM or Docker)
  pkg: minikube
  post-install: null
  post-remove: null
  pre-install: null
  pre-remove: null
  remove: null
  status: UnInstalled
